package in.co.prateekjain.resume;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.view.RedirectView;

import java.io.IOException;

@Controller
public class MainCotroller {

	@RequestMapping("/")
	public String home()
	{
		return "index.html";
	}
	
	@RequestMapping(value= "/sendMail", method = RequestMethod.GET)
	public ModelAndView sendMail(@RequestParam(value = "contactName")String contactName,@RequestParam(value = "contactEmail") String contactEmail, @RequestParam(value = "contactSubject")String contactSubject, @RequestParam(value = "contactMessage")String contactMessage) throws IOException
		{

//		Email from = new Email("contact@prateekjain.co.in");
//	    String subject = contactSubject;
//	    Email to = new Email("prateekjainbitm@gmail.com");
//	    Content content = new Content("text/plain","Name: "+contactName+"\nSubject: "+contactSubject+"\nEmail: "+contactEmail+"\nMessage: "+contactMessage);
//	    Mail mail = new Mail(from, subject, to, content);
//
//	    SendGrid sg = new SendGrid("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");
//	    Request request = new Request();
//	    try {
//	      request.setMethod(Method.POST);
//	      request.setEndpoint("mail/send");
//	      request.setBody(mail.build());
//	      Response response = sg.api(request);
//	      System.out.println(response.getStatusCode());
//	      System.out.println(response.getBody());
//	      System.out.println(response.getHeaders());
//	    } catch (IOException ex) {
//	      throw ex;
//	    }
//	    
//	    Email from1 = new Email("contact@prateekjain.co.in");
//	    String subject1 = "Details Recieved Successfully.";
//	    Email to1 = new Email(contactEmail);
//	    Content content1 = new Content("text/plain","Hello Sir/Madam,\nThanks for contacting me.\nThe following Details have been recieved successfully \nName: "+contactName+"\nSubject: "+contactSubject+"\nEmail: "+contactEmail+"\nMessage: "+contactMessage+"\n\nI will get back to you soon.\n\nRegards\nPrateek\n\n\n\n\nNote:This is an autogenerated email in response to the details submitted by you at http://www.prateekjain.co.in.");
//	    Mail mail1 = new Mail(from1, subject1, to1, content1);
//
//	    SendGrid sg1 = new SendGrid(System.getenv("SENDGRID_API_KEY"));
//	    Request request1 = new Request();
//	    try {
//	      request.setMethod(Method.POST);
//	      request.setEndpoint("mail/send");
//	      request.setBody(mail1.build());
//	      Response response1 = sg1.api(request);
//	      System.out.println(response1.getStatusCode());
//	      System.out.println(response1.getBody());
//	      System.out.println(response1.getHeaders());
//	    } catch (IOException ex) {
//	      throw ex;
//	    }
		
		
		
	    RedirectView redirectView = new RedirectView("/");
	    redirectView.setExposePathVariables(false);
	    return new ModelAndView(redirectView);
	  
	}
	
	
	
}

